"""Frozen physical constants and official study values for Task 9."""

from __future__ import annotations

import math


SPEED_OF_LIGHT_M_S = 299_792_458.0
PLANCK_CONSTANT_J_S = 6.626_070_15e-34
ELEMENTARY_CHARGE_C = 1.602_176_634e-19
ELECTRON_MASS_KG = 9.109_383_7139e-31

JOULES_PER_KEV = 1_000.0 * ELEMENTARY_CHARGE_C
KEV_PER_JOULE = 1.0 / JOULES_PER_KEV

ELECTRON_REST_ENERGY_J = ELECTRON_MASS_KG * SPEED_OF_LIGHT_M_S**2
ELECTRON_REST_ENERGY_KEV = ELECTRON_REST_ENERGY_J * KEV_PER_JOULE
ELECTRON_COMPTON_WAVELENGTH_M = (
    PLANCK_CONSTANT_J_S / (ELECTRON_MASS_KG * SPEED_OF_LIGHT_M_S)
)
CLASSICAL_ELECTRON_RADIUS_M = 2.817_940_3205e-15
BARN_M2 = 1.0e-28
THOMSON_CROSS_SECTION_M2 = (
    8.0 * math.pi * CLASSICAL_ELECTRON_RADIUS_M**2 / 3.0
)

RADIANS_PER_DEGREE = math.pi / 180.0
DEGREES_PER_RADIAN = 180.0 / math.pi

OFFICIAL_INCIDENT_ENERGIES_KEV = (50.0, 100.0, 200.0, 500.0, 1_000.0)
PHOTON_SCATTERING_ANGLE_MIN_DEG = 0.0
PHOTON_SCATTERING_ANGLE_MAX_DEG = 180.0
FORWARD_RECOIL_ANGLE_LIMIT_DEG = 90.0
BACKSCATTER_RECOIL_ANGLE_DEG = 0.0


__all__ = [
    "BACKSCATTER_RECOIL_ANGLE_DEG",
    "BARN_M2",
    "CLASSICAL_ELECTRON_RADIUS_M",
    "DEGREES_PER_RADIAN",
    "ELECTRON_COMPTON_WAVELENGTH_M",
    "ELECTRON_MASS_KG",
    "ELECTRON_REST_ENERGY_J",
    "ELECTRON_REST_ENERGY_KEV",
    "ELEMENTARY_CHARGE_C",
    "FORWARD_RECOIL_ANGLE_LIMIT_DEG",
    "JOULES_PER_KEV",
    "KEV_PER_JOULE",
    "OFFICIAL_INCIDENT_ENERGIES_KEV",
    "PHOTON_SCATTERING_ANGLE_MAX_DEG",
    "PHOTON_SCATTERING_ANGLE_MIN_DEG",
    "PLANCK_CONSTANT_J_S",
    "RADIANS_PER_DEGREE",
    "SPEED_OF_LIGHT_M_S",
    "THOMSON_CROSS_SECTION_M2",
]
