"""Frozen physical constants and exact unit conversions for Task 6."""

from __future__ import annotations

import math


PLANCK_CONSTANT_J_S_STRING = "6.62607015e-34"
ELEMENTARY_CHARGE_C_STRING = "1.602176634e-19"
ELECTRON_MASS_KG_STRING = "9.1093837139e-31"
SPEED_OF_LIGHT_M_S_STRING = "299792458"

PLANCK_CONSTANT_J_S = float(PLANCK_CONSTANT_J_S_STRING)
ELEMENTARY_CHARGE_C = float(ELEMENTARY_CHARGE_C_STRING)
ELECTRON_MASS_KG = float(ELECTRON_MASS_KG_STRING)
SPEED_OF_LIGHT_M_S = float(SPEED_OF_LIGHT_M_S_STRING)

V_PER_KV = 1000.0
M_PER_NM = 1.0e-9
M_PER_PM = 1.0e-12
M_PER_MM = 1.0e-3
RAD_PER_DEG = math.pi / 180.0
DEG_PER_RAD = 180.0 / math.pi
INV_SQRT_TWO = 1.0 / math.sqrt(2.0)


__all__ = [
    "DEG_PER_RAD",
    "ELECTRON_MASS_KG",
    "ELECTRON_MASS_KG_STRING",
    "ELEMENTARY_CHARGE_C",
    "ELEMENTARY_CHARGE_C_STRING",
    "INV_SQRT_TWO",
    "M_PER_MM",
    "M_PER_NM",
    "M_PER_PM",
    "PLANCK_CONSTANT_J_S",
    "PLANCK_CONSTANT_J_S_STRING",
    "RAD_PER_DEG",
    "SPEED_OF_LIGHT_M_S",
    "SPEED_OF_LIGHT_M_S_STRING",
    "V_PER_KV",
]
