"""Frozen mathematical constants and official reference values for Task 8."""

from __future__ import annotations

import math


RADIANS_PER_DEGREE = math.pi / 180.0
DEGREES_PER_RADIAN = 180.0 / math.pi
POLARISATION_PERIOD_DEG = 180.0

PROBABILITY_MINIMUM = 0.0
PROBABILITY_MAXIMUM = 1.0

OFFICIAL_THETA_DEG = -30.0
OFFICIAL_PHI_DEG = 30.0
OFFICIAL_CLASSICAL_MISMATCH = 3.0 / 8.0
OFFICIAL_QUANTUM_MISMATCH = 3.0 / 4.0
OFFICIAL_SIGNED_DIFFERENCE = 3.0 / 8.0

SIMULATION_MINIMUM_PHOTON_PAIRS = 10
SIMULATION_MAXIMUM_PHOTON_PAIRS = 100_000
SIMULATION_DEFAULT_PHOTON_PAIRS = 1_000
SIMULATION_DEFAULT_SEED = 2_026
UINT32_MODULUS = 2**32
UINT32_MAXIMUM = UINT32_MODULUS - 1
WILSON_95_Z = 1.959963984540054
CLASSICAL_STREAM_SALT = 0x243F6A88
QUANTUM_STREAM_SALT = 0xB7E15162


__all__ = [
    "DEGREES_PER_RADIAN",
    "OFFICIAL_CLASSICAL_MISMATCH",
    "OFFICIAL_PHI_DEG",
    "OFFICIAL_QUANTUM_MISMATCH",
    "OFFICIAL_SIGNED_DIFFERENCE",
    "OFFICIAL_THETA_DEG",
    "POLARISATION_PERIOD_DEG",
    "PROBABILITY_MAXIMUM",
    "PROBABILITY_MINIMUM",
    "RADIANS_PER_DEGREE",
    "CLASSICAL_STREAM_SALT",
    "QUANTUM_STREAM_SALT",
    "SIMULATION_DEFAULT_PHOTON_PAIRS",
    "SIMULATION_DEFAULT_SEED",
    "SIMULATION_MAXIMUM_PHOTON_PAIRS",
    "SIMULATION_MINIMUM_PHOTON_PAIRS",
    "UINT32_MAXIMUM",
    "UINT32_MODULUS",
    "WILSON_95_Z",
]
