"""Frozen physical constants for the ideal Task 5 Bohr model."""

from __future__ import annotations


PLANCK_CONSTANT_TEXT = "6.62607015e-34"
SPEED_OF_LIGHT_TEXT = "299792458"
ELEMENTARY_CHARGE_TEXT = "1.602176634e-19"
RYDBERG_CONSTANT_TEXT = "10973731.568157"

PLANCK_CONSTANT_J_S = float(PLANCK_CONSTANT_TEXT)
SPEED_OF_LIGHT_M_S = float(SPEED_OF_LIGHT_TEXT)
ELEMENTARY_CHARGE_C = float(ELEMENTARY_CHARGE_TEXT)
ELECTRONVOLT_J = ELEMENTARY_CHARGE_C
RYDBERG_CONSTANT_PER_M = float(RYDBERG_CONSTANT_TEXT)

HC_J_M = PLANCK_CONSTANT_J_S * SPEED_OF_LIGHT_M_S
HC_EV_M = HC_J_M / ELECTRONVOLT_J
HC_EV_NM = HC_EV_M * 1.0e9
RYDBERG_ENERGY_J = HC_J_M * RYDBERG_CONSTANT_PER_M
RYDBERG_ENERGY_EV = RYDBERG_ENERGY_J / ELECTRONVOLT_J
RYDBERG_WAVELENGTH_M = 1.0 / RYDBERG_CONSTANT_PER_M
RYDBERG_WAVELENGTH_NM = RYDBERG_WAVELENGTH_M * 1.0e9
METRES_PER_NANOMETRE = 1.0e-9
NANOMETRES_PER_METRE = 1.0e9


__all__ = [
    "ELECTRONVOLT_J",
    "ELEMENTARY_CHARGE_C",
    "ELEMENTARY_CHARGE_TEXT",
    "HC_EV_M",
    "HC_EV_NM",
    "HC_J_M",
    "METRES_PER_NANOMETRE",
    "NANOMETRES_PER_METRE",
    "PLANCK_CONSTANT_J_S",
    "PLANCK_CONSTANT_TEXT",
    "RYDBERG_CONSTANT_PER_M",
    "RYDBERG_CONSTANT_TEXT",
    "RYDBERG_ENERGY_EV",
    "RYDBERG_ENERGY_J",
    "RYDBERG_WAVELENGTH_M",
    "RYDBERG_WAVELENGTH_NM",
    "SPEED_OF_LIGHT_M_S",
    "SPEED_OF_LIGHT_TEXT",
]
