"""Frozen physical constants and exact conversions for Task 7."""

from __future__ import annotations

import math


PLANCK_CONSTANT_J_S_STRING = "6.62607015e-34"
ELEMENTARY_CHARGE_C_STRING = "1.602176634e-19"
ELECTRON_MASS_KG_STRING = "9.1093837139e-31"

PLANCK_CONSTANT_J_S = float(PLANCK_CONSTANT_J_S_STRING)
ELEMENTARY_CHARGE_C = float(ELEMENTARY_CHARGE_C_STRING)
ELECTRON_MASS_KG = float(ELECTRON_MASS_KG_STRING)
REDUCED_PLANCK_CONSTANT_J_S = PLANCK_CONSTANT_J_S / (2.0 * math.pi)

ELECTRONVOLT_J = ELEMENTARY_CHARGE_C
M_PER_NM = 1.0e-9


__all__ = [
    "ELECTRONVOLT_J",
    "ELECTRON_MASS_KG",
    "ELECTRON_MASS_KG_STRING",
    "ELEMENTARY_CHARGE_C",
    "ELEMENTARY_CHARGE_C_STRING",
    "M_PER_NM",
    "PLANCK_CONSTANT_J_S",
    "PLANCK_CONSTANT_J_S_STRING",
    "REDUCED_PLANCK_CONSTANT_J_S",
]
